# ----------------------------------------------------------------
# Defaults

[defaults]
filter = "submitted" # Default user filter. Other values: comments
sort = "top" # Default sorting, applies to everything. Other values: hot, new, top, rising
top_interval = "day" # Default time interval for "top" sorting. Other values: day, week, month, year, all

# ----------------------------------------------------------------
# Subs

# The leading "subs" marks a sub, followed by the sub name. Here "popular" is the default sub
# presented as Reddit's home page
[subs."popular"]
sort = "best" # Or hot, new, top, rising

# A subreddit with time interval applied (only available for "top" sorting)
[subs."worldnews"]
sort = "top"
top_interval = "hour" # Or day, week, month, year, all

# A subreddit which uses default values
[subs."programming"]

# Combine multiple sub
[subs."programming+ProgrammerHumor"]

# ----------------------------------------------------------------
# Users

# The leading "users" marks a user, followed by the username
[users."AutoModerator"]
filter = "submitted" # Or comments

# A user with time interval applied on comments (only available for "top" sorting)
[users."ilovebeer"]
filter = "comments"
sort = "top" # Or hot, new. Also applicable for "submitted" filter
top_interval = "hour" # Or day, week, month, year, all

# A user which uses default values
[users."bughunter"]

# ----------------------------------------------------------------
# Domains

# The leading "domains" marks a domain, followed by the domain name
[domains."epoc.fr"]
sort = "hot" # Or new, rising, controversial, top
top_interval = "hour" # Or day, week, month, year, all
